In [1]:
import numpy as np

gamma=0.5
actions=[
    [(1,-1,0.5),(2,0,0.5)],
    [[1,-1,0.5],[3,-2,0.5]],
    [(4,-2,0.5),(5,0,0.5)],
    [(((2,0.2),(3,0.4),(4,0.4)),1,0.5),(5,10,0.5)],
    []
]

In [2]:
def MDP2MRP(actions):
    value=np.zeros(len(actions))
    p=np.zeros((len(actions),len(actions)))
    # 初始化数组
    for i in range(len(actions)):
        for action in actions[i]:
            value[i]+=action[2] * action[1]
            # 每一步的决策收益x决策概率
            if type(action[0])==int:
                p[i][action[0]-1]+=action[2]
                # 固定目标决策，P(s'|s,a)==1
            else:
                for sub in action[0]:
                    p[i][sub[0]-1]+=action[2]*sub[1]
                    # 非固定目标决策
            
    return (value,p)
value,p=MDP2MRP(actions)
display(value,p)

array([-0.5, -1.5, -1. ,  5.5,  0. ])

array([[0.5, 0.5, 0. , 0. , 0. ],
       [0.5, 0. , 0.5, 0. , 0. ],
       [0. , 0. , 0. , 0.5, 0.5],
       [0. , 0.1, 0.2, 0.2, 0.5],
       [0. , 0. , 0. , 0. , 0. ]])

In [3]:
def bellman(gamma,value,p):
    return np.linalg.inv(np.eye(value.shape[0])-gamma*p).dot(value)
bellman(gamma,value,p)

array([-1.22555411, -1.67666232,  0.51890482,  6.0756193 ,  0.        ])

In [4]:
othor_actions=[
    [(1,-1,0.6),(2,0,0.4)],
    [(1,-1,0.3),(3,-2,0.7)],
    [(4,-2,0.5),(5,0,0.5)],
    [(((2,0.2),(3,0.4),(4,0.4)),1,0.9),(5,10,0.1)],
    []
]
# 另一个动作矩阵
value,p=MDP2MRP(othor_actions)
display(value,p)
bellman(gamma,value,p)

array([-0.6, -1.7, -1. ,  1.9,  0. ])

array([[0.6 , 0.4 , 0.  , 0.  , 0.  ],
       [0.3 , 0.  , 0.7 , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.5 , 0.5 ],
       [0.  , 0.18, 0.36, 0.36, 0.1 ],
       [0.  , 0.  , 0.  , 0.  , 0.  ]])

array([-1.45585051, -2.09547678, -0.50599771,  1.97600915,  0.        ])

In [5]:
def move(action,gamma,begin,max_step=1000):
    sum=0
    gama=1
    begin-=1
    while len(action[begin])>0:
        k=np.random.choice(range(len(action[begin])), 1, [act[2] for act in action[begin]])[0]
        # 随机出下一可能动作
        present=action[begin][k]
        sum+=gama*present[1]
        if type(present[0])==int:
            begin=present[0]-1
        else: 
            k=np.random.choice(range(len(present[0])), 1, [des[1] for des in present[0]])[0]
            # 若是非固定目标动作，随机出目标
            begin=present[0][k][0]-1
        gama*=gamma
    return sum

move(actions,gamma,2)

-2.0

In [6]:
def motkar(action,gamma):
    mot=[]
    for i in range(1,len(action)+1):
        sum=0
        total=1000
        for cnt in range(total):
            sum+=move(action,gamma,i)
        sum/=total
        # 求平均数
        mot.append(sum)
    return mot

motkar(actions,gamma)

[-1.228485365548593,
 -1.6444799898082347,
 0.44423182974080555,
 6.074707844991237,
 0.0]

In [7]:
motkar(othor_actions,gamma)

[-1.2384790590372323,
 -1.6861149441393646,
 0.4420467117729131,
 5.891063663482666,
 0.0]